### PR TITLE
add course calendar

### PR DESCRIPTION
**Pull request by cgreene**

### CODE REVIEW

**Comment by cgreene** [comment]
closes issue #43

**Comment by katrinleinweber** [comment]
Dear @cgreene,

did you convert the GCal to Markdown table manually or somehow automatically? In the latter case, would you be so kind to point me to that converter?

Kind regards!

**Comment by cgreene** [comment]
Hi @katrinleinweber - we used this: https://www.tablesgenerator.com/markdown_tables

I wish there was some way to get a google calendar to markdown!

**Comment by katrinleinweber** [comment]
There is advice on how to "[convert ICS into table](https://stackoverflow.com/questions/48709853/convert-ics-into-table-awk)" using `awk`. Maybe useful ;-)

I'm interested in the other way: hand-writing the MD table & generating a `.ics` file that people can subscribe to 🤔

**Comment by cgreene** [comment]
Oh - that'd be very convenient - I would love to see that get implemented!

**Pull request merged**
